apiVersion: apps/v1
kind: Deployment
metadata:
  name: shields
  namespace: kubebadges
  labels:
    app: shields
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shields
  template:
    metadata:
      labels:
        app: shields
    spec:
      containers:
        - name: shieldsio
          image: shieldsio/shields:next
          ports:
            - name: tcp-http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
