apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: neosu/kubebadges
    newName: neosu/kubebadges
    newTag: v0.0.3
  - name: shieldsio/shields
    newName: shieldsio/shields
    newTag: next

resources:
  - ./crd
  - ./namespace
  - ./rbac
  - ./service
  - ./deployment
