apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubebadges
  namespace: {{ .Values.namespace | default "kubebadges" }}
  labels:
    app: kubebadges
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubebadges
  template:
    metadata:
      labels:
        app: kubebadges
    spec:
      containers:
        - name: kubebadges
          image: "{{ .Values.image.kubebadges.repository }}:{{ .Values.image.kubebadges.tag }}"
          imagePullPolicy: {{ .Values.image.kubebadges.pullPolicy }}
          ports:
            - name: http-internal
              containerPort: 8090
              protocol: TCP
            - name: http-external
              containerPort: 8080
              protocol: TCP
          env:
            - name: SHIELDS_HOST
              value: {{ .Values.env.SHIELDS_HOST }}
            - name: SHIELDS_SCHEME
              value: {{ .Values.env.SHIELDS_SCHEME }}
            - name: CACHE_TIME
              value: {{ .Values.env.CACHE_TIME }}
            - name: BADGE_CACHE_TIME
              value: {{ .Values.env.BADGE_CACHE_TIME }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: kubebadges
      serviceAccount: kubebadges
