apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubebadges-rolebinding
  namespace: {{ .Values.namespace | default "kubebadges" }}
subjects:
  - kind: ServiceAccount
    name: kubebadges
    namespace: {{ .Values.namespace | default "kubebadges" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubebadges-role
