apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubebadges-role
  namespace: {{ .Values.namespace | default "kubebadges" }}
rules:
  - verbs:
      - "*"
    apiGroups:
      - kubebadges.tcode.ltd
    resources:
      - kubebadges
  - verbs:
      - "*"
    apiGroups:
      - ""
    resources:
      - configmaps
