apiVersion: v1
kind: Service
metadata:
  name: kubebadges
  namespace: {{ .Values.namespace | default "kubebadges" }}
spec:
  ports:
    - name: http-external
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-internal
      protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: kubebadges
  type: ClusterIP
  sessionAffinity: None
