apiVersion: v1
kind: Service
metadata:
  name: shields
  namespace: {{ .Values.namespace | default "kubebadges" }}
spec:
  ports:
    - name: http-shields
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: shields
  type: ClusterIP
