# Default values for kubebadges.

# Image configuration for kubebadges and shields
image:
  kubebadges:
    repository: neosu/kubebadges
    tag: v0.0.5
    pullPolicy: IfNotPresent
  shields:
    repository: shieldsio/shields
    tag: next
    pullPolicy: IfNotPresent

# Environment variables for container configuration
env:
  # Hostname and port for Shields service
  SHIELDS_HOST: "shields:8080"
  # Protocol used by the Shields service
  SHIELDS_SCHEME: "http"
  # General cache time in seconds for the kubebadges service
  CACHE_TIME: "300"
  # Cache time for badges in seconds, for the same badge
  BADGE_CACHE_TIME: "300"

# Resource limits and requests for kubebadges
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 8Mi