apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubebadges-rolebinding
  namespace: kubebadges
subjects:
  - kind: ServiceAccount
    name: kubebadges
    namespace: kubebadges
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubebadges-role
